### ISSUE TITLE
A minor typo in Ch05 - Importing Unhandled Data Objects/importing-rds-files/06-deserialize-plots-object-from-rds-in-power-bi.R

### ISSUE THREAD

**Issue by AnttiRask** [PacktPublishing/Extending-Power-BI-with-Python-and-R-2nd-edition#1]
This line:

`project_folder = "D:\\<your-path>\\Chapter04\\importing-pkl-files"`

should probably look like this:

`project_folder = "D:\\<your-path>\\Chapter05\\importing-pkl-files"`

since we're in Chapter 5, not Chapter 4.

**Comment by lucazav** [comment]
Thank you, Antti! You're definitely right. It is a typo.
